name: Terraform Resource Group Creation

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    # Step 3: Log in to Azure using the Azure CLI
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    # Step 4: Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Step 5: Apply Terraform to create resource group
    - name: Terraform Apply
      run: terraform apply -auto-approve
