name: Terraform Azure Deployment

on:
  push:
    branches:
      - main
 
 

permissions:
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    # Step 3: Log in to Azure using the Service Principal credentials
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}        # Service Principal Client ID
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}  # Service Principal Client Secret
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}        # Azure Tenant ID
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  

    # Step 4: Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Step 5: Validate Terraform configuration
    - name: Terraform Validate
      run: terraform validate

    # Step 6: Apply Terraform configuration
    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
