name: Terraform Azure Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    # Step 3: Log in to Azure using the Service Principal credentials
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 4: Get secrets from Azure Key Vault
    - name: Get secrets from Key Vault
      id: get_secrets
      uses: azure/get-keyvault-secrets@v1
      with:
        keyvault: hardik-keyvault
        secrets: my-secret

    # Step 5: Export the secret to the environment variable
    - name: Export secret to environment
      run: |
        echo "MY_SECRET=${{ steps.get_secrets.outputs.my-secret }}" >> $GITHUB_ENV

    # Step 6: Use the secret in later steps
    - name: Use the secret
      run: echo "The secret value is $MY_SECRET"

    # Step 7: Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Step 8: Validate Terraform configuration
    - name: Terraform Validate
      run: terraform validate

    # Step 9: Apply Terraform configuration
    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        MY_SECRET: ${{ secrets.MY_SECRET }} # Use the secret in Terraform or other steps
